
name: Gradle Package

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Install prerequisites
      run:
        sudo
        DEBIAN_FRONTEND=noninteractive
        apt-get -y --no-install-recommends install
          siege

    - uses: actions/checkout@v2

    - name: Checkout utils
      uses: actions/checkout@v2
      with:
        repository: org-crac/utils
        token: ${{ secrets.PACKAGES }}
        path: utils

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - run: ./gradlew assemble
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES }}

    - name: Test on Vanila JDK
      run: |
        P=$(utils/start-bg.sh \
          -s "Startup completed" \
          java -jar build/libs/example-0.1-all.jar)
        curl localhost:8080/hello/test | grep "Hello test!"
        utils/bench.sh http://localhost:8080/hello/test
        kill $P

    - name: Download JDK
      run: |
        utils/download-jdk.sh
        sudo tar -axf jdk.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES }}

    - name: Prepare warm checkpoint
      run: |
        P=$(utils/start-bg.sh \
        -s "Startup completed" \
        -e exitcode \
          jdk/bin/java \
          -Zcheckpoint:cr \
          -XX:+UnlockDiagnosticVMOptions \
          -XX:+CRTraceStartupTime \
          -Djdk.crac.trace-startup-time=true \
          -jar build/libs/example-0.1-all.jar)

        # warmup the service
        siege -b -c 1 -r 100000 http://localhost:8080/hello/test > /dev/null
        jcmd $P JDK.checkpoint
        [ 137 = $(utils/read-exitcode.sh exitcode) ]

    - name: Test on C/RaC
      run: |
        P=$(utils/start-bg.sh \
          -s "restore-finish" \
          jdk/bin/java -Zrestore:cr)
        curl localhost:8080/hello/test | grep "Hello test!"
        utils/bench.sh http://localhost:8080/hello/test
        kill $P

    - name: Test C/RaC startup time
      run:
        timeout 3 bash -c "jdk/lib/javatime ; jdk/bin/java -Zrestore:cr"
        | utils/sel.awk -v from=prestart -v to=restore-finish
